#!/usr/bin/env python
import os
import sys

env = SConscript("library/godot-cpp/SConstruct")

env.Append(CPPPATH=["source/"])
env.Append(CXXFLAGS=["-std=c++20", "-Iinclude/"])
sources = Glob("source/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "zappy/bin/libgdexample.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "zappy/bin/libgdexample{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
