---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-ast
          - id: name-tests-test
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.12.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.3
      hooks:
          - id: ruff
          - id: ruff-format
